services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '99:5432'  
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local 